version: "3"
services:
  app:
   container_name: my-blog-backend
   restart: always
   build: ./my-blog-backend
   ports:
    - "8000:8000"
   depends_on:
    - mongo

  client:
   container_name: my-blog
   restart: always
   build: ./my-blog
   ports:
    - "3000:3000"
   links:
    - app

  mongo:
   container_name: mongo-blog
   image: mongo
   restart: always
   expose:
    - "27017"
   volumes:
    - ./data:/data/db
   ports:
    - "27017:27017"